language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12.7"
  - "iojs"
install:
  - npm install --no-optional
  - npm install coveralls istanbul mocha mocha-lcov-reporter supertest

after_success:
- npm run coveralls

cache:
  directories:
    - node_modules